spring.application.name=htx
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:mysql://45.252.248.23:3306/gwnegizb_htx_lamhhong
spring.datasource.username=gwnegizb_gwnegizb
spring.datasource.password=N[wr;kUI(ND9uq}@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# SQL Init Script
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.defer-datasource-initialization=true
logging.file.name=logs/spring.log
server.error.include-message=always
server.error.include-exception=true
